# Generated by Django 3.0.3 on 2020-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200413_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='put_comment',
            field=models.CharField(default='hai', max_length=200),
            preserve_default=False,
        ),
    ]
